name: Hello World

# Controls when the workflow will run and what triggers
on:
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        uses: nagengtm/hello-world-github-action@v1.0
        with: 
          who-to-greet: 'Test Action'
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"

