name: KICS

# Controls when the workflow will run and what triggers
on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: mkdir -p myResults
    # Scan Iac with kics
    - name: run kics Scan
      uses: checkmarx/kics-action@v1.4
      with:
        # scanning serverless
        path: 'serverless'
        output_path: myResults
    # Display the results in json format
    - name: display kics results
      run: |
        cat myResults/results.json