name: Test

# Controls when the workflow will run and what triggers
on:
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello World
        uses: ./
        with: 
          greet: 'Test Action'


